services:
  flagd:
    container_name: flagd
    image: ghcr.io/open-feature/flagd:latest
    command: start --uri file:/etc/flagd/flags.flagd.json
    ports:
      - "8013:8013"
    volumes:
      - ./flags.flagd.json:/etc/flagd/flags.flagd.json

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
